name: Docker Image CD

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    #- uses: actions/checkout@v3
    - name: checkout and run docker image
      run: |
        docker login 
