name: bikeshare CD

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["bikeshare CI"]
    types:
      - completed

jobs:

  build:

    runs-on: [self-hosted]

    steps:  
    
    - name: Build and push Docker image
      run: |
        sudo docker pull paavansundar/iisc:latest
        
