name: Docker Image CD

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Python package"]
    types:
      - completed

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    #- uses: actions/checkout@v3
    - name: Log into registry 
      uses: docker/login-action@v2.1.0
      with:
          #registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_UID }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
    
    
    - name: Build and push Docker image
      run: |
        docker pull paavansundar/iisc:latest
        docker run paavansundar/iisc:latest 
